name: Deploy to GitHub Pages

on:
  push:
    branches: [final_back_front_Merged]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Dependencies and Build Frontend
        run: |
          cd client
          npm install
          npm run build

      - name: Deploy to GitHub Pages
        run: |
          cd client
          npx gh-pages -d dist
